name: nftwhisper
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        run: |-
        curl -d '{"query":"query MarketStatsCollections($sort: StatsGenTokSortInput, $take: Int, $skip: Int) {\n  marketStats {\n    generativeTokens(sort: $sort, take: $take, skip: $skip) {\n      floor\n      secVolumeTz\n      secVolumeNb\n      secVolumeTz24\n      secVolumeNb24\n      secVolumeTz7d\n      secVolumeNb7d\n      secVolumeTz30d\n      secVolumeNb30d\n      primVolumeTz\n      primVolumeNb\n      lowestSold\n      highestSold\n      median\n      listed\n      generativeToken {\n        id\n        name\n        metadata\n        author {\n          id\n          name\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n","variables":{}}' -X POST 'https://api.fxhash.xyz/graphql' -H 'Content-Type': 'application/json'
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push

