name: nftwhisper
on:
  schedule:
    - cron: "9 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        run: |
          curl -H 'Content-Type: application/json' \ -X POST -d '{"query":"fragment Author on GenerativeToken {\n author {\n id\n name\n type\n avatarUri\n flag\n collaborators {\n id\n name\n avatarUri\n flag\n __typename\n }\n __typename\n }\n __typename\n}\n\nquery Listings($skip: Int, $take: Int, $sort: ListingsSortInput, $filters: ListingFilter) {\n listings(skip: $skip, take: $take, sort: $sort, filters: $filters) {\n id\n version\n price\n objkt {\n id\n version\n name\n slug\n metadata\n duplicate\n activeListing {\n id\n version\n price\n __typename\n }\n owner {\n id\n name\n flag\n avatarUri\n __typename\n }\n issuer {\n flag\n name\n ...Author\n __typename\n }\n __typename\n }\n __typename\n }\n}\n","variables":{}}' https://api.fxhash.xyz/graphql | jq . > fxhash.json
      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push

